package:
  name: modular-composer
  version: 1.0.0

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - pybind11 >=2.10
    - cmake
    - ninja
  run:
    - python
    - music21 >=8.2
    - pyyaml >=6.0
    - pretty_midi >=0.2
    - pybind11 >=2.10

about:
  license: MIT
  summary: OtoKotoba Modular Composer
