site_name: ModCompose
site_url: https://harusan.github.io/modular-composer
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.annotate
  language: en
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Auto-Tag & Augmentation: auto_tag_aug.md
  - GUI v2 Walkthrough: gui_v2_walkthrough.md
  - Evaluation Metrics: evaluation_metrics.md
  - Plugin Guide: plugin_guide.md
  - Generator Usage: generator_usage.md
  - Effects & Automation:
      - Overview: effects.md
      - Offline IR Convolution: offline_ir.md
      - Audio Pipeline: audio_pipeline.md
  - Tone & Dynamics: tone.md
  - Piano Delta: piano_delta.md
  - Piano Epsilon: piano_epsilon.md
  - Humanizer Reference: humanizer.md
  - Live Tips: live_tips.md
  - Vocal Generator: vocal_generator.md
  - Sax Generator: sax_generator.md
  - API Reference:
      - modular_composer: api/modular_composer.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
markdown_extensions:
  - admonition
  - codehilite
  - toc
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harusan/modular-composer
  footer: "© 2025 Harusan / ModCompose"
