nbins: 16
targets:
  global:
  - 0.004718
  - 0.014828
  - 0.036621
  - 0.070546
  - 0.07796
  - 0.095709
  - 0.086722
  - 0.072568
  - 0.085149
  - 0.059313
  - 0.070995
  - 0.064255
  - 0.068075
  - 0.04381
  - 0.03078
  - 0.117951
  downbeat:
  - 0.000442
  - 0.006637
  - 0.026549
  - 0.05
  - 0.054425
  - 0.073009
  - 0.048673
  - 0.056195
  - 0.074779
  - 0.066372
  - 0.086283
  - 0.09292
  - 0.106637
  - 0.070354
  - 0.043805
  - 0.14292
  offbeat:
  - 0.001163
  - 0.006977
  - 0.016279
  - 0.034884
  - 0.109302
  - 0.165116
  - 0.204651
  - 0.111628
  - 0.105814
  - 0.033721
  - 0.019767
  - 0.02907
  - 0.017442
  - 0.015116
  - 0.018605
  - 0.110465
  prefill:
  - 0.010114
  - 0.020228
  - 0.059418
  - 0.103666
  - 0.058154
  - 0.072061
  - 0.054362
  - 0.082174
  - 0.10493
  - 0.078382
  - 0.099874
  - 0.055626
  - 0.045512
  - 0.042984
  - 0.022756
  - 0.08976
range_factors:
  dynamic_range:
    min: 28.0
    max: 118.0
  phase_adjust_db:
    downbeat: -0.4
    offbeat: 0.25
    prefill: 0.1
tempo_bins:
  - max_bpm: 95
    targets:
      global:
        - 0.02
        - 0.03
        - 0.045
        - 0.07
        - 0.085
        - 0.1
        - 0.095
        - 0.08
        - 0.075
        - 0.065
        - 0.055
        - 0.05
        - 0.045
        - 0.035
        - 0.025
        - 0.08
      downbeat:
        - 0.01
        - 0.02
        - 0.035
        - 0.05
        - 0.07
        - 0.09
        - 0.1
        - 0.11
        - 0.105
        - 0.09
        - 0.08
        - 0.075
        - 0.06
        - 0.045
        - 0.035
        - 0.09
      offbeat:
        - 0.015
        - 0.025
        - 0.03
        - 0.045
        - 0.07
        - 0.1
        - 0.12
        - 0.11
        - 0.105
        - 0.075
        - 0.055
        - 0.04
        - 0.03
        - 0.022
        - 0.018
        - 0.119
      prefill:
        - 0.012
        - 0.02
        - 0.035
        - 0.06
        - 0.082
        - 0.095
        - 0.09
        - 0.085
        - 0.08
        - 0.07
        - 0.065
        - 0.055
        - 0.045
        - 0.035
        - 0.025
        - 0.064
    range_factors:
      dynamic_range:
        min: 30.0
        max: 120.0
      phase_adjust_db:
        downbeat: -0.6
        offbeat: 0.35
        prefill: 0.12
  - max_bpm: 130
    targets:
      global:
        - 0.01
        - 0.018
        - 0.035
        - 0.06
        - 0.078
        - 0.09
        - 0.09
        - 0.082
        - 0.08
        - 0.075
        - 0.07
        - 0.065
        - 0.058
        - 0.048
        - 0.04
        - 0.101
      downbeat:
        - 0.005
        - 0.015
        - 0.03
        - 0.048
        - 0.06
        - 0.08
        - 0.09
        - 0.095
        - 0.1
        - 0.095
        - 0.09
        - 0.085
        - 0.07
        - 0.055
        - 0.04
        - 0.142
      offbeat:
        - 0.01
        - 0.02
        - 0.03
        - 0.045
        - 0.09
        - 0.14
        - 0.16
        - 0.13
        - 0.11
        - 0.06
        - 0.045
        - 0.03
        - 0.022
        - 0.018
        - 0.02
        - 0.12
      prefill:
        - 0.015
        - 0.025
        - 0.05
        - 0.08
        - 0.075
        - 0.085
        - 0.08
        - 0.082
        - 0.085
        - 0.078
        - 0.07
        - 0.055
        - 0.045
        - 0.035
        - 0.025
        - 0.084
    range_factors:
      dynamic_range:
        min: 26.0
        max: 116.0
      phase_adjust_db:
        downbeat: -0.5
        offbeat: 0.3
        prefill: 0.15
  - max_bpm: null
    targets:
      global:
        - 0.005
        - 0.012
        - 0.025
        - 0.045
        - 0.07
        - 0.09
        - 0.105
        - 0.1
        - 0.095
        - 0.09
        - 0.08
        - 0.075
        - 0.065
        - 0.045
        - 0.035
        - 0.063
      downbeat:
        - 0.003
        - 0.01
        - 0.025
        - 0.04
        - 0.06
        - 0.08
        - 0.095
        - 0.105
        - 0.11
        - 0.1
        - 0.095
        - 0.09
        - 0.075
        - 0.058
        - 0.045
        - 0.108
      offbeat:
        - 0.012
        - 0.018
        - 0.025
        - 0.04
        - 0.08
        - 0.125
        - 0.155
        - 0.145
        - 0.12
        - 0.07
        - 0.05
        - 0.032
        - 0.024
        - 0.018
        - 0.017
        - 0.089
      prefill:
        - 0.02
        - 0.03
        - 0.055
        - 0.08
        - 0.07
        - 0.075
        - 0.07
        - 0.072
        - 0.075
        - 0.07
        - 0.06
        - 0.05
        - 0.04
        - 0.03
        - 0.022
        - 0.071
    range_factors:
      dynamic_range:
        min: 24.0
        max: 112.0
      phase_adjust_db:
        downbeat: -0.45
        offbeat: 0.22
        prefill: 0.06
