pipeline:
  version: "stage2.v2025.10"
  threshold: 50.0

score:
  axes:
    timing: 2.0
    velocity: 2.0
    groove_harmony: 1.0
    drum_cohesion: 1.0
    structure: 1.0
    articulation: 1.0
  aliases_path: "../aliases/axes.yaml"
  velocity:
    target_histograms_path: "configs/thresholds/velocity_targets.yaml"
    nbins: 16
    prefill_window_beats: 0.5
    weights:
      global: 0.4
      downbeat: 0.25
      offbeat: 0.2
      prefill: 0.15
    metric_weights:
      js: 0.5
      cos: 0.5
  structure:
    grid_divisions: 16
    periodicity_candidates: [4, 8, 12, 16]
    weights:
      periodicity: 0.45
      diversity: 0.35
      density: 0.2
    density_bands:
      - max_bpm: 95
        low: 2.0
        high: 6.0
      - max_bpm: 130
        low: 4.0
        high: 9.0
      - max_bpm: null
        low: 6.0
        high: 12.0

paths:
  input_dir: "."
  metadata_dir: "output/drumloops_metadata"
  metadata_index: "output/drumloops_metadata/drumloops_metadata_v2.pickle"
  output_dir: "output/drumloops_stage2"
  events_parquet: "canonical_events.parquet"
  events_csv_sample: "canonical_events_sample.csv"
  loop_summary_csv: "loop_summary.csv"
  metrics_jsonl: "metrics_score.jsonl"
  retry_dir: "retries"
  summary_out: "stage2_summary.json"
  sample_event_rows: 5000

metrics:
  ghost_velocity_threshold: 45
  accent_velocity_threshold: 100
  microtiming_tolerance_ratio: 0.2
  swing_min_pairs: 2
  min_base_step: 1
  max_breakpoints: 3
  round_digits: 4

retry_presets: []

articulation:
  thresholds_path: "configs/thresholds/articulation.auto.yaml"
