pipeline:
  version: "stage2.v2025.10"
  threshold: 50.0

score:
  axes:
    timing: 2.0
    velocity: 2.0
    groove_harmony: 1.0
    drum_cohesion: 1.0
    structure: 1.2
    articulation: 1.0
  aliases_path: "../aliases/axes.yaml"
  velocity:
    target_histograms_path: "configs/thresholds/velocity_targets.yaml"
    nbins: 16
    prefill_window_beats: 0.5
    normalize_dynamic_range: true
    phase_compensation: true
    weights:
      global: 0.35
      downbeat: 0.30
      offbeat: 0.20
      prefill: 0.15
    metric_weights:
      js: 0.6
      cos: 0.4
    tempo_adaptive:
      bins:
        - max_bpm: 95
          alpha: 0.9
          downbeat_boost: 0.0
        - max_bpm: 130
          alpha: 1.0
          downbeat_boost: 0.02
        - max_bpm: null
          alpha: 1.10
          downbeat_boost: 0.045
  structure:
    grid_divisions: 16
    periodicity_candidates: [4, 8, 12, 16]
    weights:
      periodicity: 0.40
      diversity: 0.30
      density: 0.15
      role_stability: 0.15
    density_bands:
      - max_bpm: 95
        low: 2.0
        high: 6.0
      - max_bpm: 130
        low: 4.0
        high: 10.0
      - max_bpm: null
        low: 6.0
        high: 12.0

paths:
  input_dir: "."
  metadata_dir: "output/drumloops_metadata"
  metadata_index: "output/drumloops_metadata/drumloops_metadata_v2.pickle"
  output_dir: "output/drumloops_stage2"
  events_parquet: "canonical_events.parquet"
  events_csv_sample: "canonical_events_sample.csv"
  loop_summary_csv: "loop_summary.csv"
  metrics_jsonl: "metrics_score.jsonl"
  retry_dir: "retries"
  summary_out: "stage2_summary.json"
  sample_event_rows: 5000

metrics:
  ghost_velocity_threshold: 45
  accent_velocity_threshold: 100
  microtiming_tolerance_ratio: 0.2
  swing_min_pairs: 2
  min_base_step: 1
  max_breakpoints: 3
  round_digits: 4

retry_presets:
  - reason: velocity_chain
    when:
      axes_raw.velocity: "< 0.25"
    action:
      preset: vel_chain
      params:
        vmin: 30
        vmax: 118
        compress: 0.80
        boost_compress: 0.70
        boost_lo: 34
        boost_hi: 120
  - reason: velocity
    when:
      axes_raw.velocity: "< 0.35"
    action:
      preset: vel_smooth
      params:
        vmin: 30
        vmax: 112
        compress: 0.82
  - reason: structure
    when:
      axes_raw.structure: "< 0.30"
    action:
      preset: role_snap
      params:
        strength: 0.5
        min_gap_beats: 0.25
  - reason: timing
    when:
      axes_raw.timing: "< 0.40"
    action:
      preset: microtiming_fix
      params:
        max_shift_ms: 18
        quant_grid: "1/16"

articulation:
  thresholds_path: "configs/thresholds/articulation.auto.yaml"
