plugin: "vg_iron2"
play_range:
  low: 40
  high: 88
keyswitch:
  down_strum: 36
  up_strum: 37
  mute: 38
  arp_a: 39
section_styles:
  verse: ["down_strum"]
  chorus: ["down_strum", "up_strum"]
  bridge: ["mute", "arp_a"]
