max_epochs: 30
default_root_dir: outputs
callbacks:
  - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    init_args:
      monitor: val_loss
      patience: 5
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 1
      monitor: val_loss
      mode: min
