# Minimal configuration for a short sax demo
global_settings:
  time_signature: "4/4"
  tempo_bpm: 96
  key_tonic: "F"
  key_mode: "major"

paths:
  chordmap_path: "../data/processed_chordmap_with_emotion.yaml"
  rhythm_library_path: "../data/rhythm_library.yml"
  arrangement_overrides_path: "../data/arrangement_overrides.json"
  output_dir: "../midi_output"

sections_to_generate:
  - "Sax Solo"

part_defaults:
  melody:
    generator: sax
    seed: 123
    rhythm_key: sax_basic_swing
    growl: true
    altissimo: false
