# Default configuration for ML velocity training

input_dim: 3
batch_size: 32
epochs: 50
learning_rate: 0.001
num_workers: 0
data:
  train: tests/data/velocity_mini.csv
  val: tests/data/velocity_mini.csv
wandb: false
patience: 10

trainer:
  # Lightning の max_epochs に対応。デフォルトは root の epochs を引き継ぐ
  max_epochs: ${epochs}
  # チェックポイントやログの出力ディレクトリ
  default_root_dir: ./outputs
  # デバイス設定（必要なら追加／オーバーライド可能）
  # accelerator: mps
  # devices: 1
  # logger: …
  # callbacks: …
