name: Groove Quick Test
on: [push, pull_request]

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env: ${{ matrix.env }}
    strategy:
      matrix:
        include:
          - env:
              PURE_PY: '1'
          - env:
              CYTHON: '1'
              MCY_USE_CYTHON: '1'
          - env:
              AI: '1'
              TRANSFORMERS_OFFLINE: '1'
              HF_DATASETS_OFFLINE: '1'
          - env:
              CYTHON: '1'
              AI: '1'
              MCY_USE_CYTHON: '1'
              TRANSFORMERS_OFFLINE: '1'
              HF_DATASETS_OFFLINE: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip/wheels/**/cyext*
          key: ${{ runner.os }}-cyext-${{ hashFiles('cyext/**.pyx') }}
      - run: |
          for i in 1 2 3; do
            sudo apt-get update && sudo apt-get install -y fluid-soundfont-gm && break || sleep 5
          done
      - name: Install test dependencies (pure Python)
        if: matrix.env.PURE_PY == '1'
        run: |
          pip install -e .[test] --no-build-isolation
          pip install -r requirements-test.txt
      - name: Install test dependencies (Cython/AI)
        if: matrix.env.PURE_PY != '1'
        run: |
          MCY_USE_CYTHON=1 pip install -e .[ai,audio,test]
          pip install -r requirements-test.txt
      - name: Install hdbscan
        run: |
          pip install hdbscan
      - name: Install transformers
        if: matrix.env.AI == '1'
        run: |
          pip install --no-cache-dir --prefer-binary transformers
      - name: Install torch CPU wheel
        run: |
          for i in 1 2 3; do
            pip install torch --no-cache-dir --index-url https://download.pytorch.org/whl/cpu && break || sleep 5
          done
      - name: Install Cython
        run: |
          for i in 1 2 3; do
            pip install Cython && break || sleep 5
          done
      - name: build cyext
        run: |
          if [ "${{ matrix.env.CYTHON }}" = '1' ]; then
            python setup.py build_ext --inplace
          else
            echo "skip C extension build"
          fi
      - name: make loops
        run: |
          python - <<'PY'
          import pretty_midi, os
          os.makedirs('mini_loops', exist_ok=True)
          for i in range(2):
              pm = pretty_midi.PrettyMIDI(initial_tempo=120)
              inst = pretty_midi.Instrument(program=0, is_drum=True)
              inst.notes.append(pretty_midi.Note(velocity=100, pitch=36, start=0.0, end=0.1))
              pm.instruments.append(inst)
              pm.write(f'mini_loops/{i}.mid')
          PY
      - run: timeout 180 modcompose groove train mini_loops --order 2
      - run: pytest -x -q tests -k "not slow"
