name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install --no-interaction --no-root
      - run: poetry build
      - id: create
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload wheel
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: dist/*.whl
          asset_name: $(basename dist/*.whl)
          asset_content_type: application/octet-stream

      - name: Upload sdist
        uses: actions/upload-release-asset@v4
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: dist/*.tar.gz
          asset_name: $(basename dist/*.tar.gz)
          asset_content_type: application/gzip
